[server]
host = "0.0.0.0"
port = 8080
log_level = "info"
data_dir = "./data"
temp_dir = "./tmp"

[uploads]
max_file_size_mb = 100
allowed_types = ["image/png", "image/jpeg", "video/mp4", "image/webp", "image/gif", "image/jpg"]

[security]
token_required = true
api_key = "supersecureapikey"
rate_limit_per_minute = 60

[debug]
enabled = true

[advanced]
cache_endpoint = "http://cache.noverna.de"
cache_nodes = ["http://cache-node-1.noverna.de"]

cdn_endpoint = "https://cdn.noverna.dev" # Primary Entrypoint
cdn_nodes = ["http://cdn-node-1.local", "http://cdn-node-2.local"] # Optional: If you dont have an Loadbalancer and want to use your own CDN Server
